DROP TABLE IF EXISTS cards;
DROP TABLE IF EXISTS decks;

CREATE TABLE decks(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    userId TEXT NOT NULL
);

CREATE TABLE cards(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    deckId INTEGER NOT NULL,
    pokemonId INTEGER NOT NULL,
    name TEXT NOT NULL,
    image TEXT NOT NULL
);